# Generated by Django 2.2.6 on 2019-10-18 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, choices=[('ro', 'Roll'), ('pr', 'Promocion'), ('po', 'Postre')], default='ro', help_text='categoria del producto', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombrep', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.IntegerField()),
                ('tipop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.Tipo')),
            ],
        ),
    ]
