# Generated by Django 2.2.6 on 2019-10-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/img/medios.png', upload_to='static/img/'),
        ),
    ]
